### ISSUE TITLE
Release at Pale Moon website

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [ariacorrente/qrcodeOpenSearchPlugin#3]
Pale Moon has thier own site for search plugin, so it’s possible to provide a release for Pale Moon users, you can create your account before you publish to there:
https://addons.palemoon.org/panel/

**Comment by ariacorrente** [comment]
I tried to submit the Search Plugin through the tool you linked but it is not possible to upload a search plugins. Search plugins are handled manually by the admins and they refused this plugin. More info on this forum thread: https://forum.palemoon.org/viewtopic.php?f=46&t=24106

To allow to install this search plugin easily on any browser, I added it to the Mycroft Project:
https://mycroftproject.com/search-engines.html?name=goqr
