### ISSUE TITLE
Switch to WebExtension

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [ariacorrente/qrcodeOpenSearchPlugin#4]
Mozilla decided to deprecate OpenSearch and eventually remove it from Firefox, and the Search Engine add-ons will be removed from AMO on December 5, 2019. They also proposed to use search overrides API as a replacement, which is WebExtensions API that offers users more controls for opting into changes.

See: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/chrome_settings_overrides

**Comment by ariacorrente** [comment]
Thanks for the proposal but I think it's not worth it to develop a WebExtension to use this search plugin. There are already many extensions that can encode qrcode locally without requiring an external web service.

Search plugins are still supported on Firefox, Mozilla for now only stopped to publish this kind of feature on AMO. To allow to install this search plugin easily on any browser, I added it to the Mycroft Project:
https://mycroftproject.com/search-engines.html?name=goqr
